spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/medical_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=America/Los_Angeles&useSSL=false&allowPublicKeyRetrieval=true
    username: medical
    password: medical123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: none

server:
  port: 8080

logging:
  level:
    com.example.medical: debug

okta:
  client-id:
  client-secret:
  issuer-uri:

app:
  rate-limit:
    enabled: false
