spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=America/Chicago

server:
  port: 8080

logging:
  level:
    com.example.medical: debug
